// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuxjjuzljmwesmadrckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eGpqdXpsam13ZXNtYWRyY2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODE4NzUsImV4cCI6MjA2ODg1Nzg3NX0.THC4HJz18C9k1mS6t_4yEJeFJD4QdIQ8xwd26QRwaG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
